//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoA.App.v3.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoA.App.v3.Resources.MessageInfo", typeof(MessageInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shark.
        /// </summary>
        internal static string animal1 {
            get {
                return ResourceManager.GetString("animal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monkey.
        /// </summary>
        internal static string animal2 {
            get {
                return ResourceManager.GetString("animal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} _____________ but not a {1}..
        /// </summary>
        internal static string completeAnimal {
            get {
                return ResourceManager.GetString("completeAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hit it again!.
        /// </summary>
        internal static string messageWinner {
            get {
                return ResourceManager.GetString("messageWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lives in the water.
        /// </summary>
        internal static string questionAnimal1 {
            get {
                return ResourceManager.GetString("questionAnimal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What animal did you think?.
        /// </summary>
        internal static string questionAnimalName {
            get {
                return ResourceManager.GetString("questionAnimalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The animal you thought is the {0}?.
        /// </summary>
        internal static string questionYesOrNoAnimal {
            get {
                return ResourceManager.GetString("questionYesOrNoAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string titleComplete {
            get {
                return ResourceManager.GetString("titleComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string titleConfirm {
            get {
                return ResourceManager.GetString("titleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desist.
        /// </summary>
        internal static string titleDesist {
            get {
                return ResourceManager.GetString("titleDesist", resourceCulture);
            }
        }
    }
}
